blank_issues_enabled: false
contact_links:
  - name: Document
    url: https://sfajs.com
    about: Find the answer in the document first.
  - name: sfajs/core
    url: https://github.com/sfajs/core
    about: This is a problem of @sfajs/core.
  - name: sfajs/router
    url: https://github.com/sfajs/router
    about: This is a problem of @sfajs/router.
  - name: sfajs/view
    url: https://github.com/sfajs/view
    about: This is a problem of @sfajs/view.
  - name: sfajs/filter
    url: https://github.com/sfajs/filter
    about: This is a problem of @sfajs/filter.
  - name: Questions & Discussions
    url: https://github.com/sfajs/core/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
