blank_issues_enabled: false
contact_links:
  - name: Document
    url: https://ipare.com
    about: Find the answer in the document first.
  - name: ipare/core
    url: https://github.com/ipare/core
    about: This is a problem of @ipare/core.
  - name: ipare/router
    url: https://github.com/ipare/router
    about: This is a problem of @ipare/router.
  - name: ipare/view
    url: https://github.com/ipare/view
    about: This is a problem of @ipare/view.
  - name: ipare/filter
    url: https://github.com/ipare/filter
    about: This is a problem of @ipare/filter.
  - name: Questions & Discussions
    url: https://github.com/ipare/core/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
